---
services:
  rtorrent_exporter:
    image: "aauren/rtorrent_exporter:2024071001"
    container_name: rtorrent_exporter
    restart: unless-stopped
    ports:
      - 9135:9135
    command:
      # You'll want to ensure that:
      # - 172.28.1.0/24 is a subnet that is not in use on your network (if it is, then change this and the IPAM config below)
      # - You don't have any host firewalls that block traffic to/from this subnet to your rtorrent URL
      - "-rtorrent.addr"
      - "https://172.28.1.1/RPC2"
      # Optional
      # If you use HTTP basic authentication with your rtorrent XMLRPC URL
      # - "-rtorrent.username"
      # - "<username>"
      # - "-rtorrent.password"
      # - "<password>"
      # If you use a self-signed certificate with your rtorrent XMLRPC URL
      # - "rtorrent.insecure"
      # - "true"
      # If you want to tune any timeouts
      # - "-rtorrent.timeout"
      # - "5s"
      # - "-telemetry.timeout"
      # - "5s"
      # If you want to disable high cardinality metrics, but lose some visibility into individual torrent metrics
      # - "-rtorrent.downloads.collect.details"
      # - "false"
networks:
  rtorrent_exporter:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.1
