---
services:
  rtorrent_exporter:
    image: "aauren/rtorrent_exporter:2024071001"
    container_name: rtorrent_exporter
    restart: unless-stopped
    ports:
      - 9135:9135
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "-rtorrent.addr"
      - "https://host.docker.internal/RPC2"
      # Optional
      # - "-rtorrent.username"
      # - "<username>"
      # - "-rtorrent.password"
      # - "<password>"
      # - "rtorrent.insecure"
      # - "true"
