{
 "title": "rtorrent",
 "description": "Metrics for rtorrent torrent client",
 "tags": [
  "torrent",
  "p2p"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prom", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "rtorrent_counts",
    "label": "Count Stats to Display",
    "query": "active, complete, error, hashing, incomplete, leeching, seeding, started, stopped"
   }
  ]
 },
 "panels": [
  {
   "title": "$rtorrent_counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "rtorrent_counts",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtorrent_downloads_$rtorrent_counts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrent Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rtorrent_downloads", "legendFormat": "downloads" },
    { "expr": "rtorrent_downloads_active", "legendFormat": "active" },
    { "expr": "rtorrent_downloads_completete", "legendFormat": "complete" },
    { "expr": "rtorrent_downloads_hashing", "legendFormat": "hashing" },
    { "expr": "rtorrent_downloads_incomplete", "legendFormat": "incomplete" },
    { "expr": "rtorrent_downloads_leeching", "legendFormat": "leeching" },
    { "expr": "rtorrent_downloads_seeding", "legendFormat": "seeding" },
    { "expr": "rtorrent_downloads_started", "legendFormat": "started" },
    { "expr": "rtorrent_downloads_stopped", "legendFormat": "stopped" },
    { "expr": "rtorrent_downloads_error", "legendFormat": "error" }
   ]
  },
  {
   "title": "Torrent Upload / Download Rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(rtorrent_downloads_upload_total_bytes[$__rate_interval])",
     "legendFormat": "Upload: {{name}}"
    },
    {
     "expr": "increase(rtorrent_downloads_download_total_bytes[$__rate_interval])",
     "legendFormat": "Download: {{name}}"
    }
   ]
  },
  {
   "title": "Torrent Upload / Download Rates (by tracker)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(rtorrent_downloads_upload_total_bytes[$__rate_interval])) by (tracker)",
     "legendFormat": "Upload: {{tracker}}"
    },
    {
     "expr": "sum(increase(rtorrent_downloads_download_total_bytes[$__rate_interval])) by (tracker)",
     "legendFormat": "Download: {{tracker}}"
    }
   ]
  },
  {
   "title": "Tracker Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rtorrent_downloads_messages) by (name, message)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Torrent Numbers (Over Current Range)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(rtorrent_downloads_upload_total_bytes[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(rtorrent_downloads_download_total_bytes[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rtorrent_downloads_upload_total_bytes / rtorrent_downloads_download_total_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Popular Torrents (Most Time Spent Uploading)",
   "type": "piechart",
   "description": "Torrents that are most consistently uploading over the given range",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(changes(rtorrent_downloads_upload_total_bytes[$__range])) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Uploaded Variable (by Tracker)",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(rtorrent_downloads_upload_total_bytes[$__range])) by (tracker))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Uploaded Variable",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(rtorrent_downloads_upload_total_bytes[$__range])) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Uploaded Last 2 Weeks",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(rtorrent_downloads_upload_total_bytes[$__range])) by (name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}